config:
  outputs: |
    [OUTPUT]
        Name            forward
        Match           *
        Host            ${fluentd_service_name}
        Port            24224
        
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi 