serviceAccount:
  create: true

service:
  ports:
    - name: forward
      protocol: TCP
      containerPort: 24224

fileConfigs:
  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type elasticsearch
        host "elasticsearch-master"
        port 9200
        path ""
        user elastic
        password changeme
        # Don't wait for elastic to start up.
        verify_es_version_at_startup false
      </match>
    </label>

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi 